// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-workspace/internal/controller/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkspaceService creates a new instance of MockWorkspaceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceService {
	mock := &MockWorkspaceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaceService is an autogenerated mock type for the WorkspaceService type
type MockWorkspaceService struct {
	mock.Mock
}

type MockWorkspaceService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceService) EXPECT() *MockWorkspaceService_Expecter {
	return &MockWorkspaceService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockWorkspaceService
func (_mock *MockWorkspaceService) Create(ctx context.Context, namespace string, req service.CreateWorkspaceRequest) (*service.WorkspaceDetail, error) {
	ret := _mock.Called(ctx, namespace, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *service.WorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.CreateWorkspaceRequest) (*service.WorkspaceDetail, error)); ok {
		return returnFunc(ctx, namespace, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, service.CreateWorkspaceRequest) *service.WorkspaceDetail); ok {
		r0 = returnFunc(ctx, namespace, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.WorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, service.CreateWorkspaceRequest) error); ok {
		r1 = returnFunc(ctx, namespace, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWorkspaceService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - req service.CreateWorkspaceRequest
func (_e *MockWorkspaceService_Expecter) Create(ctx interface{}, namespace interface{}, req interface{}) *MockWorkspaceService_Create_Call {
	return &MockWorkspaceService_Create_Call{Call: _e.mock.On("Create", ctx, namespace, req)}
}

func (_c *MockWorkspaceService_Create_Call) Run(run func(ctx context.Context, namespace string, req service.CreateWorkspaceRequest)) *MockWorkspaceService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 service.CreateWorkspaceRequest
		if args[2] != nil {
			arg2 = args[2].(service.CreateWorkspaceRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceService_Create_Call) Return(workspaceDetail *service.WorkspaceDetail, err error) *MockWorkspaceService_Create_Call {
	_c.Call.Return(workspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceService_Create_Call) RunAndReturn(run func(ctx context.Context, namespace string, req service.CreateWorkspaceRequest) (*service.WorkspaceDetail, error)) *MockWorkspaceService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWorkspaceService
func (_mock *MockWorkspaceService) Delete(ctx context.Context, namespace string, name string) error {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkspaceService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockWorkspaceService_Expecter) Delete(ctx interface{}, namespace interface{}, name interface{}) *MockWorkspaceService_Delete_Call {
	return &MockWorkspaceService_Delete_Call{Call: _e.mock.On("Delete", ctx, namespace, name)}
}

func (_c *MockWorkspaceService_Delete_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockWorkspaceService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceService_Delete_Call) Return(err error) *MockWorkspaceService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceService_Delete_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) error) *MockWorkspaceService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWorkspaceService
func (_mock *MockWorkspaceService) Get(ctx context.Context, namespace string, name string) (*service.WorkspaceDetail, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *service.WorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*service.WorkspaceDetail, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *service.WorkspaceDetail); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.WorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkspaceService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockWorkspaceService_Expecter) Get(ctx interface{}, namespace interface{}, name interface{}) *MockWorkspaceService_Get_Call {
	return &MockWorkspaceService_Get_Call{Call: _e.mock.On("Get", ctx, namespace, name)}
}

func (_c *MockWorkspaceService_Get_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockWorkspaceService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceService_Get_Call) Return(workspaceDetail *service.WorkspaceDetail, err error) *MockWorkspaceService_Get_Call {
	_c.Call.Return(workspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceService_Get_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*service.WorkspaceDetail, error)) *MockWorkspaceService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkspaceService
func (_mock *MockWorkspaceService) List(ctx context.Context, namespace string) ([]service.WorkspaceSummary, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []service.WorkspaceSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]service.WorkspaceSummary, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []service.WorkspaceSummary); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.WorkspaceSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkspaceService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockWorkspaceService_Expecter) List(ctx interface{}, namespace interface{}) *MockWorkspaceService_List_Call {
	return &MockWorkspaceService_List_Call{Call: _e.mock.On("List", ctx, namespace)}
}

func (_c *MockWorkspaceService_List_Call) Run(run func(ctx context.Context, namespace string)) *MockWorkspaceService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceService_List_Call) Return(workspaceSummarys []service.WorkspaceSummary, err error) *MockWorkspaceService_List_Call {
	_c.Call.Return(workspaceSummarys, err)
	return _c
}

func (_c *MockWorkspaceService_List_Call) RunAndReturn(run func(ctx context.Context, namespace string) ([]service.WorkspaceSummary, error)) *MockWorkspaceService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockWorkspaceService
func (_mock *MockWorkspaceService) Resume(ctx context.Context, namespace string, name string) (*service.WorkspaceDetail, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 *service.WorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*service.WorkspaceDetail, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *service.WorkspaceDetail); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.WorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceService_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockWorkspaceService_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockWorkspaceService_Expecter) Resume(ctx interface{}, namespace interface{}, name interface{}) *MockWorkspaceService_Resume_Call {
	return &MockWorkspaceService_Resume_Call{Call: _e.mock.On("Resume", ctx, namespace, name)}
}

func (_c *MockWorkspaceService_Resume_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockWorkspaceService_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceService_Resume_Call) Return(workspaceDetail *service.WorkspaceDetail, err error) *MockWorkspaceService_Resume_Call {
	_c.Call.Return(workspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceService_Resume_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*service.WorkspaceDetail, error)) *MockWorkspaceService_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// Suspend provides a mock function for the type MockWorkspaceService
func (_mock *MockWorkspaceService) Suspend(ctx context.Context, namespace string, name string) (*service.WorkspaceDetail, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Suspend")
	}

	var r0 *service.WorkspaceDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*service.WorkspaceDetail, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *service.WorkspaceDetail); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.WorkspaceDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceService_Suspend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Suspend'
type MockWorkspaceService_Suspend_Call struct {
	*mock.Call
}

// Suspend is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockWorkspaceService_Expecter) Suspend(ctx interface{}, namespace interface{}, name interface{}) *MockWorkspaceService_Suspend_Call {
	return &MockWorkspaceService_Suspend_Call{Call: _e.mock.On("Suspend", ctx, namespace, name)}
}

func (_c *MockWorkspaceService_Suspend_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockWorkspaceService_Suspend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceService_Suspend_Call) Return(workspaceDetail *service.WorkspaceDetail, err error) *MockWorkspaceService_Suspend_Call {
	_c.Call.Return(workspaceDetail, err)
	return _c
}

func (_c *MockWorkspaceService_Suspend_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*service.WorkspaceDetail, error)) *MockWorkspaceService_Suspend_Call {
	_c.Call.Return(run)
	return _c
}
