// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-station/pkg/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPortfolioService creates a new instance of MockPortfolioService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortfolioService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortfolioService {
	mock := &MockPortfolioService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortfolioService is an autogenerated mock type for the PortfolioService type
type MockPortfolioService struct {
	mock.Mock
}

type MockPortfolioService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortfolioService) EXPECT() *MockPortfolioService_Expecter {
	return &MockPortfolioService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPortfolioService
func (_mock *MockPortfolioService) Get(ctx context.Context, namespace string, name string) (*v1alpha1.Portfolio, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1alpha1.Portfolio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Portfolio, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Portfolio); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Portfolio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortfolioService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPortfolioService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockPortfolioService_Expecter) Get(ctx interface{}, namespace interface{}, name interface{}) *MockPortfolioService_Get_Call {
	return &MockPortfolioService_Get_Call{Call: _e.mock.On("Get", ctx, namespace, name)}
}

func (_c *MockPortfolioService_Get_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockPortfolioService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPortfolioService_Get_Call) Return(portfolio *v1alpha1.Portfolio, err error) *MockPortfolioService_Get_Call {
	_c.Call.Return(portfolio, err)
	return _c
}

func (_c *MockPortfolioService_Get_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*v1alpha1.Portfolio, error)) *MockPortfolioService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPortfolioService
func (_mock *MockPortfolioService) List(ctx context.Context, namespace string) (*v1alpha1.PortfolioList, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1alpha1.PortfolioList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1alpha1.PortfolioList, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1alpha1.PortfolioList); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.PortfolioList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortfolioService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPortfolioService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockPortfolioService_Expecter) List(ctx interface{}, namespace interface{}) *MockPortfolioService_List_Call {
	return &MockPortfolioService_List_Call{Call: _e.mock.On("List", ctx, namespace)}
}

func (_c *MockPortfolioService_List_Call) Run(run func(ctx context.Context, namespace string)) *MockPortfolioService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPortfolioService_List_Call) Return(portfolioList *v1alpha1.PortfolioList, err error) *MockPortfolioService_List_Call {
	_c.Call.Return(portfolioList, err)
	return _c
}

func (_c *MockPortfolioService_List_Call) RunAndReturn(run func(ctx context.Context, namespace string) (*v1alpha1.PortfolioList, error)) *MockPortfolioService_List_Call {
	_c.Call.Return(run)
	return _c
}
