// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-workspace/pkg/v1alpha1"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NewMockPortfolioAdapter creates a new instance of MockPortfolioAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPortfolioAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPortfolioAdapter {
	mock := &MockPortfolioAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPortfolioAdapter is an autogenerated mock type for the PortfolioAdapter type
type MockPortfolioAdapter struct {
	mock.Mock
}

type MockPortfolioAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPortfolioAdapter) EXPECT() *MockPortfolioAdapter_Expecter {
	return &MockPortfolioAdapter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockPortfolioAdapter
func (_mock *MockPortfolioAdapter) Get(ctx context.Context, namespace string, name string) (*v1alpha1.Portfolio, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1alpha1.Portfolio
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Portfolio, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Portfolio); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Portfolio)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortfolioAdapter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPortfolioAdapter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockPortfolioAdapter_Expecter) Get(ctx interface{}, namespace interface{}, name interface{}) *MockPortfolioAdapter_Get_Call {
	return &MockPortfolioAdapter_Get_Call{Call: _e.mock.On("Get", ctx, namespace, name)}
}

func (_c *MockPortfolioAdapter_Get_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockPortfolioAdapter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPortfolioAdapter_Get_Call) Return(portfolio *v1alpha1.Portfolio, err error) *MockPortfolioAdapter_Get_Call {
	_c.Call.Return(portfolio, err)
	return _c
}

func (_c *MockPortfolioAdapter_Get_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*v1alpha1.Portfolio, error)) *MockPortfolioAdapter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPortfolioAdapter
func (_mock *MockPortfolioAdapter) List(ctx context.Context, namespace string) (*v1alpha1.PortfolioList, error) {
	ret := _mock.Called(ctx, namespace)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1alpha1.PortfolioList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1alpha1.PortfolioList, error)); ok {
		return returnFunc(ctx, namespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1alpha1.PortfolioList); ok {
		r0 = returnFunc(ctx, namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.PortfolioList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, namespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortfolioAdapter_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPortfolioAdapter_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
func (_e *MockPortfolioAdapter_Expecter) List(ctx interface{}, namespace interface{}) *MockPortfolioAdapter_List_Call {
	return &MockPortfolioAdapter_List_Call{Call: _e.mock.On("List", ctx, namespace)}
}

func (_c *MockPortfolioAdapter_List_Call) Run(run func(ctx context.Context, namespace string)) *MockPortfolioAdapter_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPortfolioAdapter_List_Call) Return(portfolioList *v1alpha1.PortfolioList, err error) *MockPortfolioAdapter_List_Call {
	_c.Call.Return(portfolioList, err)
	return _c
}

func (_c *MockPortfolioAdapter_List_Call) RunAndReturn(run func(ctx context.Context, namespace string) (*v1alpha1.PortfolioList, error)) *MockPortfolioAdapter_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkspacesBySelector provides a mock function for the type MockPortfolioAdapter
func (_mock *MockPortfolioAdapter) ListWorkspacesBySelector(ctx context.Context, namespace string, selector *v1.LabelSelector) (*v1alpha1.WorkspaceList, error) {
	ret := _mock.Called(ctx, namespace, selector)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkspacesBySelector")
	}

	var r0 *v1alpha1.WorkspaceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.LabelSelector) (*v1alpha1.WorkspaceList, error)); ok {
		return returnFunc(ctx, namespace, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.LabelSelector) *v1alpha1.WorkspaceList); ok {
		r0 = returnFunc(ctx, namespace, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.WorkspaceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *v1.LabelSelector) error); ok {
		r1 = returnFunc(ctx, namespace, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPortfolioAdapter_ListWorkspacesBySelector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkspacesBySelector'
type MockPortfolioAdapter_ListWorkspacesBySelector_Call struct {
	*mock.Call
}

// ListWorkspacesBySelector is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - selector *v1.LabelSelector
func (_e *MockPortfolioAdapter_Expecter) ListWorkspacesBySelector(ctx interface{}, namespace interface{}, selector interface{}) *MockPortfolioAdapter_ListWorkspacesBySelector_Call {
	return &MockPortfolioAdapter_ListWorkspacesBySelector_Call{Call: _e.mock.On("ListWorkspacesBySelector", ctx, namespace, selector)}
}

func (_c *MockPortfolioAdapter_ListWorkspacesBySelector_Call) Run(run func(ctx context.Context, namespace string, selector *v1.LabelSelector)) *MockPortfolioAdapter_ListWorkspacesBySelector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1.LabelSelector
		if args[2] != nil {
			arg2 = args[2].(*v1.LabelSelector)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPortfolioAdapter_ListWorkspacesBySelector_Call) Return(workspaceList *v1alpha1.WorkspaceList, err error) *MockPortfolioAdapter_ListWorkspacesBySelector_Call {
	_c.Call.Return(workspaceList, err)
	return _c
}

func (_c *MockPortfolioAdapter_ListWorkspacesBySelector_Call) RunAndReturn(run func(ctx context.Context, namespace string, selector *v1.LabelSelector) (*v1alpha1.WorkspaceList, error)) *MockPortfolioAdapter_ListWorkspacesBySelector_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockPortfolioAdapter
func (_mock *MockPortfolioAdapter) UpdateStatus(ctx context.Context, p *v1alpha1.Portfolio) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Portfolio) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPortfolioAdapter_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockPortfolioAdapter_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - p *v1alpha1.Portfolio
func (_e *MockPortfolioAdapter_Expecter) UpdateStatus(ctx interface{}, p interface{}) *MockPortfolioAdapter_UpdateStatus_Call {
	return &MockPortfolioAdapter_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, p)}
}

func (_c *MockPortfolioAdapter_UpdateStatus_Call) Run(run func(ctx context.Context, p *v1alpha1.Portfolio)) *MockPortfolioAdapter_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.Portfolio
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.Portfolio)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPortfolioAdapter_UpdateStatus_Call) Return(err error) *MockPortfolioAdapter_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPortfolioAdapter_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, p *v1alpha1.Portfolio) error) *MockPortfolioAdapter_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
