// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-station/pkg/v1alpha1"
	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockWorkspaceAdapter creates a new instance of MockWorkspaceAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceAdapter {
	mock := &MockWorkspaceAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaceAdapter is an autogenerated mock type for the WorkspaceAdapter type
type MockWorkspaceAdapter struct {
	mock.Mock
}

type MockWorkspaceAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceAdapter) EXPECT() *MockWorkspaceAdapter_Expecter {
	return &MockWorkspaceAdapter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockWorkspaceAdapter
func (_mock *MockWorkspaceAdapter) Create(ctx context.Context, ws *v1alpha1.Workspace) error {
	ret := _mock.Called(ctx, ws)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Workspace) error); ok {
		r0 = returnFunc(ctx, ws)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceAdapter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWorkspaceAdapter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ws *v1alpha1.Workspace
func (_e *MockWorkspaceAdapter_Expecter) Create(ctx interface{}, ws interface{}) *MockWorkspaceAdapter_Create_Call {
	return &MockWorkspaceAdapter_Create_Call{Call: _e.mock.On("Create", ctx, ws)}
}

func (_c *MockWorkspaceAdapter_Create_Call) Run(run func(ctx context.Context, ws *v1alpha1.Workspace)) *MockWorkspaceAdapter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.Workspace
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.Workspace)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAdapter_Create_Call) Return(err error) *MockWorkspaceAdapter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceAdapter_Create_Call) RunAndReturn(run func(ctx context.Context, ws *v1alpha1.Workspace) error) *MockWorkspaceAdapter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockWorkspaceAdapter
func (_mock *MockWorkspaceAdapter) Delete(ctx context.Context, namespace string, name string) error {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceAdapter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkspaceAdapter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockWorkspaceAdapter_Expecter) Delete(ctx interface{}, namespace interface{}, name interface{}) *MockWorkspaceAdapter_Delete_Call {
	return &MockWorkspaceAdapter_Delete_Call{Call: _e.mock.On("Delete", ctx, namespace, name)}
}

func (_c *MockWorkspaceAdapter_Delete_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockWorkspaceAdapter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceAdapter_Delete_Call) Return(err error) *MockWorkspaceAdapter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceAdapter_Delete_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) error) *MockWorkspaceAdapter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWorkspaceAdapter
func (_mock *MockWorkspaceAdapter) Get(ctx context.Context, namespace string, name string) (*v1alpha1.Workspace, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1alpha1.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Workspace, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Workspace); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAdapter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWorkspaceAdapter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockWorkspaceAdapter_Expecter) Get(ctx interface{}, namespace interface{}, name interface{}) *MockWorkspaceAdapter_Get_Call {
	return &MockWorkspaceAdapter_Get_Call{Call: _e.mock.On("Get", ctx, namespace, name)}
}

func (_c *MockWorkspaceAdapter_Get_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockWorkspaceAdapter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceAdapter_Get_Call) Return(workspace *v1alpha1.Workspace, err error) *MockWorkspaceAdapter_Get_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockWorkspaceAdapter_Get_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*v1alpha1.Workspace, error)) *MockWorkspaceAdapter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockWorkspaceAdapter
func (_mock *MockWorkspaceAdapter) List(ctx context.Context, namespace string, opts ...client.ListOption) (*v1alpha1.WorkspaceList, error) {
	// client.ListOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, namespace)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1alpha1.WorkspaceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.ListOption) (*v1alpha1.WorkspaceList, error)); ok {
		return returnFunc(ctx, namespace, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...client.ListOption) *v1alpha1.WorkspaceList); ok {
		r0 = returnFunc(ctx, namespace, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.WorkspaceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...client.ListOption) error); ok {
		r1 = returnFunc(ctx, namespace, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAdapter_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockWorkspaceAdapter_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - opts ...client.ListOption
func (_e *MockWorkspaceAdapter_Expecter) List(ctx interface{}, namespace interface{}, opts ...interface{}) *MockWorkspaceAdapter_List_Call {
	return &MockWorkspaceAdapter_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, namespace}, opts...)...)}
}

func (_c *MockWorkspaceAdapter_List_Call) Run(run func(ctx context.Context, namespace string, opts ...client.ListOption)) *MockWorkspaceAdapter_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.ListOption
		variadicArgs := make([]client.ListOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(client.ListOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockWorkspaceAdapter_List_Call) Return(workspaceList *v1alpha1.WorkspaceList, err error) *MockWorkspaceAdapter_List_Call {
	_c.Call.Return(workspaceList, err)
	return _c
}

func (_c *MockWorkspaceAdapter_List_Call) RunAndReturn(run func(ctx context.Context, namespace string, opts ...client.ListOption) (*v1alpha1.WorkspaceList, error)) *MockWorkspaceAdapter_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockWorkspaceAdapter
func (_mock *MockWorkspaceAdapter) Update(ctx context.Context, ws *v1alpha1.Workspace) error {
	ret := _mock.Called(ctx, ws)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Workspace) error); ok {
		r0 = returnFunc(ctx, ws)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceAdapter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockWorkspaceAdapter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ws *v1alpha1.Workspace
func (_e *MockWorkspaceAdapter_Expecter) Update(ctx interface{}, ws interface{}) *MockWorkspaceAdapter_Update_Call {
	return &MockWorkspaceAdapter_Update_Call{Call: _e.mock.On("Update", ctx, ws)}
}

func (_c *MockWorkspaceAdapter_Update_Call) Run(run func(ctx context.Context, ws *v1alpha1.Workspace)) *MockWorkspaceAdapter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.Workspace
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.Workspace)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAdapter_Update_Call) Return(err error) *MockWorkspaceAdapter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceAdapter_Update_Call) RunAndReturn(run func(ctx context.Context, ws *v1alpha1.Workspace) error) *MockWorkspaceAdapter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockWorkspaceAdapter
func (_mock *MockWorkspaceAdapter) UpdateStatus(ctx context.Context, ws *v1alpha1.Workspace) error {
	ret := _mock.Called(ctx, ws)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1alpha1.Workspace) error); ok {
		r0 = returnFunc(ctx, ws)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceAdapter_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockWorkspaceAdapter_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - ws *v1alpha1.Workspace
func (_e *MockWorkspaceAdapter_Expecter) UpdateStatus(ctx interface{}, ws interface{}) *MockWorkspaceAdapter_UpdateStatus_Call {
	return &MockWorkspaceAdapter_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, ws)}
}

func (_c *MockWorkspaceAdapter_UpdateStatus_Call) Run(run func(ctx context.Context, ws *v1alpha1.Workspace)) *MockWorkspaceAdapter_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1alpha1.Workspace
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.Workspace)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceAdapter_UpdateStatus_Call) Return(err error) *MockWorkspaceAdapter_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceAdapter_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, ws *v1alpha1.Workspace) error) *MockWorkspaceAdapter_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
