// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewMockSecretAdapter creates a new instance of MockSecretAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretAdapter {
	mock := &MockSecretAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretAdapter is an autogenerated mock type for the SecretAdapter type
type MockSecretAdapter struct {
	mock.Mock
}

type MockSecretAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretAdapter) EXPECT() *MockSecretAdapter_Expecter {
	return &MockSecretAdapter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSecretAdapter
func (_mock *MockSecretAdapter) Create(ctx context.Context, secret *v1.Secret) error {
	ret := _mock.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Secret) error); ok {
		r0 = returnFunc(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretAdapter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSecretAdapter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - secret *v1.Secret
func (_e *MockSecretAdapter_Expecter) Create(ctx interface{}, secret interface{}) *MockSecretAdapter_Create_Call {
	return &MockSecretAdapter_Create_Call{Call: _e.mock.On("Create", ctx, secret)}
}

func (_c *MockSecretAdapter_Create_Call) Run(run func(ctx context.Context, secret *v1.Secret)) *MockSecretAdapter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Secret
		if args[1] != nil {
			arg1 = args[1].(*v1.Secret)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSecretAdapter_Create_Call) Return(err error) *MockSecretAdapter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretAdapter_Create_Call) RunAndReturn(run func(ctx context.Context, secret *v1.Secret) error) *MockSecretAdapter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSecretAdapter
func (_mock *MockSecretAdapter) Delete(ctx context.Context, namespace string, name string) error {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretAdapter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSecretAdapter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockSecretAdapter_Expecter) Delete(ctx interface{}, namespace interface{}, name interface{}) *MockSecretAdapter_Delete_Call {
	return &MockSecretAdapter_Delete_Call{Call: _e.mock.On("Delete", ctx, namespace, name)}
}

func (_c *MockSecretAdapter_Delete_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockSecretAdapter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretAdapter_Delete_Call) Return(err error) *MockSecretAdapter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretAdapter_Delete_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) error) *MockSecretAdapter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSecretAdapter
func (_mock *MockSecretAdapter) Get(ctx context.Context, namespace string, name string) (*v1.Secret, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.Secret
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*v1.Secret, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *v1.Secret); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretAdapter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSecretAdapter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockSecretAdapter_Expecter) Get(ctx interface{}, namespace interface{}, name interface{}) *MockSecretAdapter_Get_Call {
	return &MockSecretAdapter_Get_Call{Call: _e.mock.On("Get", ctx, namespace, name)}
}

func (_c *MockSecretAdapter_Get_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockSecretAdapter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSecretAdapter_Get_Call) Return(secret *v1.Secret, err error) *MockSecretAdapter_Get_Call {
	_c.Call.Return(secret, err)
	return _c
}

func (_c *MockSecretAdapter_Get_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*v1.Secret, error)) *MockSecretAdapter_Get_Call {
	_c.Call.Return(run)
	return _c
}
