// Copyright 2024 Alexandre Mahdhaoui
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build go1.22

// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/alexandremahdhaoui/forge-station/internal/controller/service"
	"github.com/alexandremahdhaoui/forge-station/pkg/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// CreateWorkspaceRequest defines model for CreateWorkspaceRequest.
type CreateWorkspaceRequest = service.CreateWorkspaceRequest

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// PortfolioSummary defines model for PortfolioSummary.
type PortfolioSummary = v1alpha1.Portfolio

// WorkspaceDetail defines model for WorkspaceDetail.
type WorkspaceDetail = service.WorkspaceDetail

// WorkspaceSummary defines model for WorkspaceSummary.
type WorkspaceSummary = service.WorkspaceSummary

// ListPortfoliosParams defines parameters for ListPortfolios.
type ListPortfoliosParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// GetPortfolioParams defines parameters for GetPortfolio.
type GetPortfolioParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ListWorkspacesParams defines parameters for ListWorkspaces.
type ListWorkspacesParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// CreateWorkspaceParams defines parameters for CreateWorkspace.
type CreateWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// DeleteWorkspaceParams defines parameters for DeleteWorkspace.
type DeleteWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// GetWorkspaceParams defines parameters for GetWorkspace.
type GetWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// ResumeWorkspaceParams defines parameters for ResumeWorkspace.
type ResumeWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// SuspendWorkspaceParams defines parameters for SuspendWorkspace.
type SuspendWorkspaceParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = CreateWorkspaceRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams)
	// Get portfolio details
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams)
	// List all workspaces
	// (GET /api/v1/workspaces)
	ListWorkspaces(w http.ResponseWriter, r *http.Request, params ListWorkspacesParams)
	// Create a new workspace
	// (POST /api/v1/workspaces)
	CreateWorkspace(w http.ResponseWriter, r *http.Request, params CreateWorkspaceParams)
	// Delete a workspace
	// (DELETE /api/v1/workspaces/{name})
	DeleteWorkspace(w http.ResponseWriter, r *http.Request, name string, params DeleteWorkspaceParams)
	// Get workspace details
	// (GET /api/v1/workspaces/{name})
	GetWorkspace(w http.ResponseWriter, r *http.Request, name string, params GetWorkspaceParams)
	// Resume a workspace
	// (PUT /api/v1/workspaces/{name}/resume)
	ResumeWorkspace(w http.ResponseWriter, r *http.Request, name string, params ResumeWorkspaceParams)
	// Suspend a workspace
	// (PUT /api/v1/workspaces/{name}/suspend)
	SuspendWorkspace(w http.ResponseWriter, r *http.Request, name string, params SuspendWorkspaceParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPortfolios operation middleware
func (siw *ServerInterfaceWrapper) ListPortfolios(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPortfoliosParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPortfolios(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetPortfolio operation middleware
func (siw *ServerInterfaceWrapper) GetPortfolio(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPortfolioParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPortfolio(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ListWorkspaces operation middleware
func (siw *ServerInterfaceWrapper) ListWorkspaces(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListWorkspacesParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWorkspaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateWorkspace operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWorkspace(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteWorkspace operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetWorkspace operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ResumeWorkspace operation middleware
func (siw *ServerInterfaceWrapper) ResumeWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ResumeWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResumeWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SuspendWorkspace operation middleware
func (siw *ServerInterfaceWrapper) SuspendWorkspace(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SuspendWorkspaceParams

	// ------------- Optional query parameter "namespace" -------------

	err = runtime.BindQueryParameter("form", true, false, "namespace", r.URL.Query(), &params.Namespace)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "namespace", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SuspendWorkspace(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios", wrapper.ListPortfolios)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/portfolios/{name}", wrapper.GetPortfolio)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/workspaces", wrapper.ListWorkspaces)
	m.HandleFunc("POST "+options.BaseURL+"/api/v1/workspaces", wrapper.CreateWorkspace)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/v1/workspaces/{name}", wrapper.DeleteWorkspace)
	m.HandleFunc("GET "+options.BaseURL+"/api/v1/workspaces/{name}", wrapper.GetWorkspace)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/workspaces/{name}/resume", wrapper.ResumeWorkspace)
	m.HandleFunc("PUT "+options.BaseURL+"/api/v1/workspaces/{name}/suspend", wrapper.SuspendWorkspace)

	return m
}

type ListPortfoliosRequestObject struct {
	Params ListPortfoliosParams
}

type ListPortfoliosResponseObject interface {
	VisitListPortfoliosResponse(w http.ResponseWriter) error
}

type ListPortfolios200JSONResponse []PortfolioSummary

func (response ListPortfolios200JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListPortfolios500JSONResponse ErrorResponse

func (response ListPortfolios500JSONResponse) VisitListPortfoliosResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolioRequestObject struct {
	Name   string `json:"name"`
	Params GetPortfolioParams
}

type GetPortfolioResponseObject interface {
	VisitGetPortfolioResponse(w http.ResponseWriter) error
}

type GetPortfolio200JSONResponse PortfolioSummary

func (response GetPortfolio200JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio404JSONResponse ErrorResponse

func (response GetPortfolio404JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPortfolio500JSONResponse ErrorResponse

func (response GetPortfolio500JSONResponse) VisitGetPortfolioResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListWorkspacesRequestObject struct {
	Params ListWorkspacesParams
}

type ListWorkspacesResponseObject interface {
	VisitListWorkspacesResponse(w http.ResponseWriter) error
}

type ListWorkspaces200JSONResponse []WorkspaceSummary

func (response ListWorkspaces200JSONResponse) VisitListWorkspacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListWorkspaces500JSONResponse ErrorResponse

func (response ListWorkspaces500JSONResponse) VisitListWorkspacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspaceRequestObject struct {
	Params CreateWorkspaceParams
	Body   *CreateWorkspaceJSONRequestBody
}

type CreateWorkspaceResponseObject interface {
	VisitCreateWorkspaceResponse(w http.ResponseWriter) error
}

type CreateWorkspace201JSONResponse WorkspaceDetail

func (response CreateWorkspace201JSONResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspace400JSONResponse ErrorResponse

func (response CreateWorkspace400JSONResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspace500JSONResponse ErrorResponse

func (response CreateWorkspace500JSONResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params DeleteWorkspaceParams
}

type DeleteWorkspaceResponseObject interface {
	VisitDeleteWorkspaceResponse(w http.ResponseWriter) error
}

type DeleteWorkspace204Response struct {
}

func (response DeleteWorkspace204Response) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteWorkspace404JSONResponse ErrorResponse

func (response DeleteWorkspace404JSONResponse) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteWorkspace500JSONResponse ErrorResponse

func (response DeleteWorkspace500JSONResponse) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params GetWorkspaceParams
}

type GetWorkspaceResponseObject interface {
	VisitGetWorkspaceResponse(w http.ResponseWriter) error
}

type GetWorkspace200JSONResponse WorkspaceDetail

func (response GetWorkspace200JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace404JSONResponse ErrorResponse

func (response GetWorkspace404JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspace500JSONResponse ErrorResponse

func (response GetWorkspace500JSONResponse) VisitGetWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ResumeWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params ResumeWorkspaceParams
}

type ResumeWorkspaceResponseObject interface {
	VisitResumeWorkspaceResponse(w http.ResponseWriter) error
}

type ResumeWorkspace200JSONResponse WorkspaceDetail

func (response ResumeWorkspace200JSONResponse) VisitResumeWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ResumeWorkspace404JSONResponse ErrorResponse

func (response ResumeWorkspace404JSONResponse) VisitResumeWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ResumeWorkspace500JSONResponse ErrorResponse

func (response ResumeWorkspace500JSONResponse) VisitResumeWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SuspendWorkspaceRequestObject struct {
	Name   string `json:"name"`
	Params SuspendWorkspaceParams
}

type SuspendWorkspaceResponseObject interface {
	VisitSuspendWorkspaceResponse(w http.ResponseWriter) error
}

type SuspendWorkspace200JSONResponse WorkspaceDetail

func (response SuspendWorkspace200JSONResponse) VisitSuspendWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SuspendWorkspace404JSONResponse ErrorResponse

func (response SuspendWorkspace404JSONResponse) VisitSuspendWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SuspendWorkspace500JSONResponse ErrorResponse

func (response SuspendWorkspace500JSONResponse) VisitSuspendWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all portfolios
	// (GET /api/v1/portfolios)
	ListPortfolios(ctx context.Context, request ListPortfoliosRequestObject) (ListPortfoliosResponseObject, error)
	// Get portfolio details
	// (GET /api/v1/portfolios/{name})
	GetPortfolio(ctx context.Context, request GetPortfolioRequestObject) (GetPortfolioResponseObject, error)
	// List all workspaces
	// (GET /api/v1/workspaces)
	ListWorkspaces(ctx context.Context, request ListWorkspacesRequestObject) (ListWorkspacesResponseObject, error)
	// Create a new workspace
	// (POST /api/v1/workspaces)
	CreateWorkspace(ctx context.Context, request CreateWorkspaceRequestObject) (CreateWorkspaceResponseObject, error)
	// Delete a workspace
	// (DELETE /api/v1/workspaces/{name})
	DeleteWorkspace(ctx context.Context, request DeleteWorkspaceRequestObject) (DeleteWorkspaceResponseObject, error)
	// Get workspace details
	// (GET /api/v1/workspaces/{name})
	GetWorkspace(ctx context.Context, request GetWorkspaceRequestObject) (GetWorkspaceResponseObject, error)
	// Resume a workspace
	// (PUT /api/v1/workspaces/{name}/resume)
	ResumeWorkspace(ctx context.Context, request ResumeWorkspaceRequestObject) (ResumeWorkspaceResponseObject, error)
	// Suspend a workspace
	// (PUT /api/v1/workspaces/{name}/suspend)
	SuspendWorkspace(ctx context.Context, request SuspendWorkspaceRequestObject) (SuspendWorkspaceResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListPortfolios operation middleware
func (sh *strictHandler) ListPortfolios(w http.ResponseWriter, r *http.Request, params ListPortfoliosParams) {
	var request ListPortfoliosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPortfolios(ctx, request.(ListPortfoliosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPortfolios")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPortfoliosResponseObject); ok {
		if err := validResponse.VisitListPortfoliosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPortfolio operation middleware
func (sh *strictHandler) GetPortfolio(w http.ResponseWriter, r *http.Request, name string, params GetPortfolioParams) {
	var request GetPortfolioRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPortfolio(ctx, request.(GetPortfolioRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPortfolio")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPortfolioResponseObject); ok {
		if err := validResponse.VisitGetPortfolioResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListWorkspaces operation middleware
func (sh *strictHandler) ListWorkspaces(w http.ResponseWriter, r *http.Request, params ListWorkspacesParams) {
	var request ListWorkspacesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListWorkspaces(ctx, request.(ListWorkspacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListWorkspaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListWorkspacesResponseObject); ok {
		if err := validResponse.VisitListWorkspacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWorkspace operation middleware
func (sh *strictHandler) CreateWorkspace(w http.ResponseWriter, r *http.Request, params CreateWorkspaceParams) {
	var request CreateWorkspaceRequestObject

	request.Params = params

	var body CreateWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkspace(ctx, request.(CreateWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateWorkspaceResponseObject); ok {
		if err := validResponse.VisitCreateWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteWorkspace operation middleware
func (sh *strictHandler) DeleteWorkspace(w http.ResponseWriter, r *http.Request, name string, params DeleteWorkspaceParams) {
	var request DeleteWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWorkspace(ctx, request.(DeleteWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteWorkspaceResponseObject); ok {
		if err := validResponse.VisitDeleteWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspace operation middleware
func (sh *strictHandler) GetWorkspace(w http.ResponseWriter, r *http.Request, name string, params GetWorkspaceParams) {
	var request GetWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspace(ctx, request.(GetWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkspaceResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ResumeWorkspace operation middleware
func (sh *strictHandler) ResumeWorkspace(w http.ResponseWriter, r *http.Request, name string, params ResumeWorkspaceParams) {
	var request ResumeWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ResumeWorkspace(ctx, request.(ResumeWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ResumeWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ResumeWorkspaceResponseObject); ok {
		if err := validResponse.VisitResumeWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SuspendWorkspace operation middleware
func (sh *strictHandler) SuspendWorkspace(w http.ResponseWriter, r *http.Request, name string, params SuspendWorkspaceParams) {
	var request SuspendWorkspaceRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SuspendWorkspace(ctx, request.(SuspendWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SuspendWorkspace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SuspendWorkspaceResponseObject); ok {
		if err := validResponse.VisitSuspendWorkspaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yYz0/rOBDH/xVrdo9p0i7sJbdlQQjp6Qm1T+KAOJhkkhoS29hOoaryvz/ZSZukaUtB",
	"qOpDPTVK/OM7Mx9/PbCASORScORGQ7gAHU0xp+7xf4XU4J1Qz1rSCMf4UqA29ouZS4QQxOMTRgY8eBuk",
	"YlC/1KhmLEJ/y+zW4AHLpVBuQUnNFEJImZkWj34k8oBm+EZ5rDCn03hKRcGCRKgUB6/LFQPGDSpOsyAS",
	"3CiRZaiCencoSw+ulBJqjFoKrtHtooREZRi68NB+bkWjjWI8dTMVvhRMYQzhfT3swVsLuvTgViiTiIyJ",
	"SZHnVM3fy8xsRDM5pSN/NfErsyGf02C5gwtilfpLNJRl+9ZtfdoBC7baes+E9iQv5x1Ms1XNeCLs8jHq",
	"SDFpmOAQwvhq8ov8d3tDEqFITjlNGU/Jal1NKI+JXIKgffDAMJPZsNYk2FXAgxkqXS09G/lDf2gJFBI5",
	"lQxCOPOH/hl4LkZHd0AlC2ajoNnCvk3RZcIeA2qF3sQQwg+mzW0zzC6iaI4GlYbwfgHMbvpSoEssp7nV",
	"aH+cOvBqy6hSkNAiMxCunrze6Xqwx6s6k07SP8Oh/bHpRe7UUSkzFjl9wZO2IS9aezCDuZv4t8IEQvgr",
	"aAwsqN0r6B3NciWEKkXn4CrXrdikiCLUOikyshRop/37QX27ZHUdaYOGm5o2YhFDRSrzseP08ki4chGa",
	"ZS163Ih+xYOFLVO5tfDXaNpWtKns7sx0qg5tezSqwDYAPSs9Nno+Bs3ekJwPzw8HyU9hSCIKHh8lntdo",
	"GjJJ7C6RLqCNCe60pLtm2HewpN4l9R0tqVXa0gMp9IbarjWGBymu6z0vRDz/srxtaW/Lbvto/bHs0TX6",
	"MhXrzdqG+q2GkMhJjiu/OiBBFzQmapmfI6S3KiWhhONrQ/AWy2rdqTFmaLAP+KV7/x7gx3+znve72iq0",
	"+HTldQCqskJoGx5va8v154MxPKR/nTqufTqu5q/F3R1XbV+BQl3k1T9Fig2Yjt3nE6mfvGmr7J5ssstp",
	"BVXXJndCqgstkcdbKZ1U30+YfhLTOr8nUNdArblaI7UsfwcAAP//ru12eiwXAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
